{
  imports = [
    ./bufferline.nix
    ./conform.nix
    ./gitsigns.nix
    ./illuminate.nix
    ./lsp.nix
    ./lualine.nix
    ./luasnip.nix
    ./mini.nix
    ./neo-tree.nix
    ./noice.nix
    ./nvim-autopairs.nix
    ./nvim-cmp.nix
    ./telescope.nix
    ./treesitter.nix
    ./vim-css-color.nix
    ./which-key.nix
  ];
}
